export let products =  [
    {
      avaiblity: true,
      stars: 2,
      review: 10,
      title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
      price: 600,
      offprice: 590,
      img: "assets/newproducts/newproduct.png",
      id: 0,
    },
    {
      avaiblity: true,
      stars: 5,
      review: 1,
      title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
      price: 600,
      offprice: 590,
      img: "assets/newproducts/newproduct (5).png",
      id: 1,
    },
    {
      avaiblity: false,
      stars: 3,
      review: 100,
      title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
      price: 600,
      offprice: 590,
      img: "assets/newproducts/newproduct (4).png",
      id: 2,
    },
    {
      avaiblity: true,
      stars: 2,
      review: 10,
      title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
      price: 600,
      offprice: 590,
      img: "assets/newproducts/newproduct (5).png",
      id: 3,
    },
    {
      avaiblity: true,
      stars: 2,
      review: 10,
      title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
      price: 600,
      offprice: 590,
      img: "assets/newproducts/newproduct (6).png",
      id: 4,
    },
    {
      avaiblity: false,
      stars: 2,
      review: 10,
      title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
      price: 600,
      offprice: 590,
      img: "assets/newproducts/newproduct.png",
      id: 5,
    },
    {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (1).png",
        id: 6,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (2).png",
        id: 7,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (3).png",
        id: 8,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (4).png",
        id: 9,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (5).png",
        id: 10,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (1).png",
        id: 11,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/MsiLaptops/MsiLaptop (2).png",
        id: 12,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/newproducts/newproduct.png",
        id: 13,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/newproducts/newproduct.png",
        id: 14,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/newproducts/newproduct.png",
        id: 15,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/newproducts/newproduct.png",
        id: 16,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/newproducts/newproduct.png",
        id: 17,
      },
      {
        avaiblity: false,
        stars: 2,
        review: 10,
        title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
        price: 600,
        offprice: 590,
        img: "assets/newproducts/newproduct.png",
        id: 18,
      },
      
  ];